### model
model_name_or_path: your_path/Qwen2.5-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: your_path/deepspeed/ds_z3_offload_config.json
flash_attn: fa2

### dataset
dataset: LIMO_QFFT
cutoff_len: 16384
overwrite_cache: true
preprocessing_num_workers: 64
template: qwen_qfft

### output
output_dir: your_path/output/limo_qfft_7B
logging_steps: 10
plot_loss: true
overwrite_output_dir: true
save_strategy: epoch
save_only_model: true


### train
per_device_train_batch_size: 1 
per_device_train_batch_size: 1  # batchsize 8
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 6
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
weight_decay: 1.0e-4
